### ISSUE TITLE
exclude instances without private keys

### ISSUE THREAD

**Issue by babatundebusari** [gianlucaborello/aws-ssh-config#12]
Getting this error for instances without private key 

```
Traceback (most recent call last):
  File "aws-ssh-config.py", line 137, in <module>
    main()
  File "aws-ssh-config.py", line 131, in main
    print '    IdentityFile ~/.ssh/' + instance.key_name + '.pem'
TypeError: cannot concatenate 'str' and 'NoneType' objects
```

Is there a way to exclude instances without the private key(s)?

**Comment by gianlucaborello** [comment]
Fixed, thanks for reporting
